# Generated by Django 3.2.7 on 2021-09-27 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=254)),
                ('address_line_2', models.CharField(blank=True, max_length=254, null=True)),
                ('town', models.CharField(max_length=70)),
                ('post_code', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('delivery_cost', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=10000)),
                ('items', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
