# Generated by Django 3.2.7 on 2021-09-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(max_length=1000),
        ),
    ]
