# Generated by Django 3.2.7 on 2021-11-19 08:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20211119_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3000), max_length=1000, size=None),
        ),
    ]
