# Generated by Django 3.2.7 on 2021-09-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210927_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
