# Generated by Django 3.2.7 on 2021-09-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='has_sizes',
            field=models.BooleanField(default=False),
        ),
    ]
